In [96]:
import numpy as np

In [97]:
data1 = [6, 7.5, 8, 0, 1]
data1


[6, 7.5, 8, 0, 1]

In [98]:
# numpy를 이용하여 1차원 배열로 변환
arr1 = np.array(data1)
# numpy array 안의 값들은 같은 타입이어야 한다.
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [99]:
# 배열 크기 확인
arr1.shape

(5,)

In [100]:
# 2차원 List 생성
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [101]:
# 2차원 List를 numpy array로 변환
arr2 = np.array(data2)
print(arr2)
print('(행, 열)', arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(행, 열) (2, 4)


In [102]:
# 0으로 채워진 1차원 배열 생성
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
np.zeros((3, 5, 2))
# (page, row, column)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [104]:
# 1로 채워진 1차원 배열 생성: 0과 1만 있음
arr4 = np.ones(10)
arr4

# 10으로 채워진 1차열 배열 생성
arr5 = np.full(10, 10)
arr5

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [105]:
# 숫자 8로 구성된 3행 5열 배열 생성
arr6 = np.full((3, 5), 8)
arr6

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [106]:
# 범위가 있는 배열 생성
arr7 = np.arange(10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2차원 배열

In [107]:
arr2d = np.arange(1, 17).reshape(4, 4) # 1~16을 4x4로 배열
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [108]:
arr2d.dtype

dtype('int64')

In [109]:
# 2번 행의 자료 출력
print(arr2d[2])
print(arr2d[2,])
print(arr2d[2,:])


[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]


In [110]:
# 1에서 2번행의 자료 출력
print(arr2d[1:2])

# 3번 열의 자료 출력
print(arr2d[:,3])

# 0, 1열의 자료 출력
print(arr2d[:,0:2])

# 1행 2열의 자료 출력
print(arr2d[1,2])

[[5 6 7 8]]
[ 4  8 12 16]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
7


In [111]:
arr2d[0:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 난수 발생
- rand: 0부터 1사이의 균일 분포
- randn: 가우시안 표준 정규 분포
- randint: 균일 분포의 정수 난수

### Boolean indexing

In [112]:
names = np.array(['Charles', 'Anne', 'David', 'John', 'Charles', 'Hayoung', 'Hayoung'])
data = np.random.randn(7, 4)
print(names)
print(names.shape)
print(data)

['Charles' 'Anne' 'David' 'John' 'Charles' 'Hayoung' 'Hayoung']
(7,)
[[ 0.50928763  0.16730381  1.31678815  0.57753302]
 [-1.35402496  0.31212244  0.39793282  0.13470556]
 [ 0.99903502 -1.69698368 -0.68872502  1.91608103]
 [ 0.11294283 -0.89506862  0.24937676 -1.02148042]
 [ 0.22643814  1.21082128  0.2839084  -0.71682472]
 [ 1.45675948 -0.08260165 -0.57001676  0.16635047]
 [ 0.09993994 -0.97531866 -0.48136967 -0.4833296 ]]


In [113]:
# Mask를 이용한 추출
mask = (names == 'Charles')
print(mask)

# data에서 mask에 해당하는 값 추출
print(data[mask])

[ True False False False  True False False]
[[ 0.50928763  0.16730381  1.31678815  0.57753302]
 [ 0.22643814  1.21082128  0.2839084  -0.71682472]]


In [114]:
data[(names == 'Charles') | (names == 'Anne'), :]

array([[ 0.50928763,  0.16730381,  1.31678815,  0.57753302],
       [-1.35402496,  0.31212244,  0.39793282,  0.13470556],
       [ 0.22643814,  1.21082128,  0.2839084 , -0.71682472]])

In [115]:
# data의 4번째 열 중 0보다 작은 것의 mask 만들기
print(data)
print('-----')
print(data[ data[:,3] < 0, :])

[[ 0.50928763  0.16730381  1.31678815  0.57753302]
 [-1.35402496  0.31212244  0.39793282  0.13470556]
 [ 0.99903502 -1.69698368 -0.68872502  1.91608103]
 [ 0.11294283 -0.89506862  0.24937676 -1.02148042]
 [ 0.22643814  1.21082128  0.2839084  -0.71682472]
 [ 1.45675948 -0.08260165 -0.57001676  0.16635047]
 [ 0.09993994 -0.97531866 -0.48136967 -0.4833296 ]]
-----
[[ 0.11294283 -0.89506862  0.24937676 -1.02148042]
 [ 0.22643814  1.21082128  0.2839084  -0.71682472]
 [ 0.09993994 -0.97531866 -0.48136967 -0.4833296 ]]


In [123]:
names = np.array(['Charles', 'Anne', 'David', 'John', 'Charles', 'Hayoung', 'Hayoung'])
data = np.random.randn(7, 4)

# data의 4번째 열의 값이 0보다 작은 행의 0~3열을 0으로 바꿈
data[data[:,3] < 0, 0:3] = 0
data

array([[ 0.        ,  0.        ,  0.        , -0.54688531],
       [-0.20106897,  0.99147484, -0.59336195,  0.75378441],
       [ 0.        ,  0.        ,  0.        , -0.66992459],
       [-1.80416695,  1.62326785, -0.52659172,  2.02797375],
       [ 1.32052977, -0.82018741,  1.69111676,  0.4382067 ],
       [ 0.        ,  0.        ,  0.        , -1.04600561],
       [ 0.        ,  0.        ,  0.        , -0.07914233]])

In [126]:
arr = np.random.rand(8)
# 오름차순 정렬
print(np.sort(arr))
# 내림차순 정렬
print(np.sort(arr)[::-1])

[0.02074518 0.2369851  0.30432373 0.56781996 0.75324554 0.77847778
 0.8156508  0.8274084 ]
[0.8274084  0.8156508  0.77847778 0.75324554 0.56781996 0.30432373
 0.2369851  0.02074518]


In [129]:
# 2차원 데이터
arr = np.random.rand(5, 3)
print(arr)

print(np.sort(arr, axis=0)) # 같은 Column 내에서 정렬
print(np.sort(arr, axis=1)) # 같은 Row 내에서 정렬

[[0.193055   0.5179033  0.87872045]
 [0.90137718 0.27858353 0.60381664]
 [0.79009747 0.80847888 0.39213614]
 [0.74121951 0.5040301  0.57792243]
 [0.31518241 0.58292375 0.80322964]]
[[0.193055   0.27858353 0.39213614]
 [0.31518241 0.5040301  0.57792243]
 [0.74121951 0.5179033  0.60381664]
 [0.79009747 0.58292375 0.80322964]
 [0.90137718 0.80847888 0.87872045]]
[[0.193055   0.5179033  0.87872045]
 [0.27858353 0.60381664 0.90137718]
 [0.39213614 0.79009747 0.80847888]
 [0.5040301  0.57792243 0.74121951]
 [0.31518241 0.58292375 0.80322964]]


In [133]:
print(np.sort(arr, axis=1))
print(np.sort(arr, axis=1)[::-1])

[[0.193055   0.5179033  0.87872045]
 [0.27858353 0.60381664 0.90137718]
 [0.39213614 0.79009747 0.80847888]
 [0.5040301  0.57792243 0.74121951]
 [0.31518241 0.58292375 0.80322964]]
[[0.31518241 0.58292375 0.80322964]
 [0.5040301  0.57792243 0.74121951]
 [0.39213614 0.79009747 0.80847888]
 [0.27858353 0.60381664 0.90137718]
 [0.193055   0.5179033  0.87872045]]


# Reshape

In [135]:
arr = np.arange(1, 11)
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [136]:
arr = np.arange(1,28).reshape(3,3,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [150]:
# 1차원으로 변경
print(arr.reshape(-1,1)) # 2차원처럼 생겼지만 딥러닝에서 이렇게 써야 함

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]]


In [152]:
arr = np.arange(1,9).reshape(2,2,2)

arr.reshape(-1,1) == arr.reshape(-1)

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])